services:
  - type: web
    name: kn-kishore-portfolio
    env: docker
    # Use pre-built image from Docker Hub
    image:
      url: docker.io/kishorenarayan11/portfolio:latest
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
